---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  # storageClassName: block-storage-retain